services:
  
type: web
  name: discord-bot
  env: python
  buildCommand: "pip install -r requirements.txt"
  startCommand: "bash start.sh"
  plan: free
  envVars:
key: DISCORD_TOKEN
    sync: false